### ISSUE TITLE
Сообщение height дублируется

### ISSUE THREAD

**Issue by maxim-klenov** [ai36/ai36.github.io#21]
debug.css > строка 85:
``` css
:has(>img:not([width]))::before {
    content: "Изображение " attr(class) " без атрибута height";
    counter-increment: debug-counter;
}
```
**Вместо height в значении свойства content предполагается width**
